[build]
builder = "DOCKERFILE"
dockerfilePath = "Backend/Dockerfile"
dockerContextDir = "Backend"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
